const NOTES=["C","C♯/Db","D","D♯/Eb","E","F","F♯/Gb","G","G♯/Ab","A","A♯/Bb","B"],OPEN=[4,11,7,2,9,4],NAMES=["E","B","G","D","A","E"];
const INTS=["P1","m2/♭9","M2/9","m3","M3","P4/11","♭5/♯11","P5","m6/♭13","M6/13","m7","M7"];
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="fretboard.css"><link rel="stylesheet" href="modes.css">');
let S={page:"home",mode:"name",strings:[1,2,3,4,5,6],from:1,to:12,count:10,notePool:[0,2,4,5,7,9,11],intPool:[3,4,7,10],deck:[],i:0,score:0,miss:[],picked:[],feedback:null,locked:false};
const app=document.querySelector("#app"),note=(s,f)=>(OPEN[s-1]+f)%12,frets=()=>Array.from({length:S.to-S.from+1},(_,i)=>S.from+i),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const header=()=>'<header class="brand"><span>12</span><div><strong>Fretboard</strong><small>Trainer</small></div></header>';
function home(){return `${header()}<section class="home-intro"><em>Practice modes</em><h1>Choose your<br>fretboard drill.</h1><p>練習モードを選択してください。今後、新しいモードをここに追加できます。</p></section><div class="mode-list">${[["name","A","Name the Note","位置から音名を答える"],["find","◎","Find the Notes","指定音をすべて探す"],["interval","M3","Name the Interval","2点間の度数を答える"]].map(x=>`<button class="mode-card" data-mode="${x[0]}"><i>${x[1]}</i><span><b>${x[2]}</b><small>${x[3]}</small></span><strong>→</strong></button>`).join("")}</div>`}
function opts(v){return Array.from({length:12},(_,i)=>i+1).map(n=>`<option ${n===v?"selected":""}>${n}</option>`).join("")}
function settings(){let title={name:"Name the Note",find:"Find the Notes",interval:"Name the Interval"}[S.mode];return `${header()}<button class="back" id="home">← Modes</button><section class="panel"><div class="intro"><em>Session setup</em><h1>${title}</h1><p>弦、フレット範囲、問題数を選択します。</p></div><fieldset><legend>Strings</legend><div class="string-grid">${[1,2,3,4,5,6].map(s=>`<button data-string="${s}" class="${S.strings.includes(s)?"selected":""}"><b>${s}</b><i>${NAMES[s-1]}</i></button>`).join("")}</div></fieldset><fieldset><legend>Fret range <small>${S.from}–${S.to}</small></legend><div class="range"><label>From<select id="from">${opts(S.from)}</select></label><span>—</span><label>To<select id="to">${opts(S.to)}</select></label></div></fieldset>${S.mode==="find"?noteOptions():""}${S.mode==="interval"?intOptions():""}<fieldset><legend>Questions</legend><div class="segments">${[10,20,50].map(n=>`<button data-count="${n}" class="${S.count===n?"selected":""}">${n}</button>`).join("")}</div></fieldset><button class="primary" id="start">Start session <span>→</span></button></section>`}
function noteOptions(){return `<fieldset><legend>Target notes</legend><div class="choice-grid">${NOTES.map((n,i)=>`<button data-note-pool="${i}" class="${S.notePool.includes(i)?"selected":""}">${n}</button>`).join("")}</div></fieldset>`}
function intOptions(){return `<fieldset><legend>Intervals</legend><div class="presets"><button data-preset="easy">Easy</button><button data-preset="basic">Basic</button><button data-preset="all">All</button></div><div class="choice-grid">${INTS.map((n,i)=>`<button data-int-pool="${i}" class="${S.intPool.includes(i)?"selected":""}">${n}</button>`).join("")}</div></fieldset>`}
function positions(){let a=[];S.strings.forEach(s=>frets().forEach(f=>a.push({string:s,fret:f,note:note(s,f)})));return a}
const repeat=(a,n)=>Array.from({length:n},(_,i)=>a[i%a.length]);
function makeDeck(){let p=positions();if(S.mode==="name")return repeat(shuffle(p),S.count);if(S.mode==="find"){let valid=S.notePool.filter(n=>p.some(x=>x.note===n));return repeat(shuffle(valid.map(note=>({note}))),S.count)}let q=[];p.forEach(r=>p.forEach(t=>{let semi=(t.note-r.note+12)%12;if(r!==t&&S.intPool.includes(semi))q.push({root:r,target:t,semi})}));return repeat(shuffle(q),S.count)}
function start(){Object.assign(S,{page:"play",deck:makeDeck(),i:0,score:0,miss:[],picked:[],feedback:null,locked:false});render()}
function board(marks=[],tap=false){let fs=frets(),ss=[...S.strings].sort((a,b)=>a-b),nut=S.from===1,pm=[3,5,7,9,12].filter(f=>fs.includes(f));return `<div class="board-wrap"><div class="fret-numbers">${nut?'<span class="nut-space"></span>':""}${fs.map(f=>`<span>${f}</span>`).join("")}</div><div class="horizontal-board" style="--rows:${ss.length}">${pm.map(f=>`<b class="position-marker" style="left:${(nut?10:0)+(f-S.from)*43+17}px"></b>`).join("")}${ss.map(s=>`<div class="guitar-string"><span class="string-label">${s}<small>${NAMES[s-1]}</small></span>${nut?'<b class="nut"></b>':""}${fs.map(f=>{let m=marks.find(x=>x.string===s&&x.fret===f),content=m?`<i class="${m.cls||""}">${m.text}</i>`:"";return tap?`<button class="fret-cell tappable" data-pos="${s},${f}" aria-label="${s}弦${f}フレット">${content}</button>`:`<div class="fret-cell">${content}</div>`}).join("")}</div>`).join("")}</div></div>`}
const progress=()=>`<div class="progress"><button id="exit">×</button><div><span style="width:${(S.i+1)/S.deck.length*100}%"></span></div><b>${S.i+1}<small> / ${S.deck.length}</small></b></div>`;
function play(){let q=S.deck[S.i],body;if(S.mode==="name"){let m={...q,text:S.feedback?NOTES[q.note]:"?",cls:S.feedback?(S.feedback.ok?"right":"wrong"):""};body=`<div class="prompt"><em>Name this note</em><h1>${q.string}弦・${q.fret}フレット</h1></div>${board([m])}<div class="answers">${NOTES.map((n,i)=>`<button data-note-answer="${i}">${n}</button>`).join("")}</div>`}else if(S.mode==="find"){let marks=[];positions().forEach(p=>{let chosen=S.picked.some(x=>x.string===p.string&&x.fret===p.fret),good=p.note===q.note;if(chosen||S.feedback&&good)marks.push({...p,text:S.feedback&&good?NOTES[q.note]:chosen?"✓":"",cls:S.feedback?(good?"right":"wrong"):"picked"})});body=`<div class="prompt"><em>Find all notes</em><h1>すべての ${NOTES[q.note]}</h1><p>範囲内の正解位置をすべてタップ</p></div>${board(marks,true)}<button class="primary submit" id="submit">Answer <span>${S.picked.length} selected</span></button>`}else{let marks=[{...q.root,text:"R",cls:"root"},{...q.target,text:S.feedback?INTS[q.semi]:"?",cls:S.feedback?(S.feedback.ok?"right":"wrong"):""}];body=`<div class="prompt"><em>Name the interval</em><h1>R から ? の度数</h1></div>${board(marks)}<div class="answers">${S.intPool.map(i=>`<button data-int-answer="${i}">${INTS[i]}</button>`).join("")}</div>`}return `${header()}${progress()}${body}<div class="feedback">${S.feedback?(S.feedback.ok?"Correct":`正解：${S.feedback.correct}`):"回答してください"}</div>`}
function done(ok,correct,detail){if(ok)S.score++;else S.miss.push(detail);S.feedback={ok,correct};S.locked=true;render();setTimeout(()=>{S.i++;S.picked=[];S.feedback=null;S.locked=false;if(S.i>=S.deck.length)S.page="result";render()},ok?650:1300)}
function submitFind(){if(!S.picked.length)return;let q=S.deck[S.i],correct=positions().filter(p=>p.note===q.note),key=x=>`${x.string}-${x.fret}`,a=S.picked.map(key).sort().join(),b=correct.map(key).sort().join();done(a===b,NOTES[q.note],NOTES[q.note])}
function result(){let pct=Math.round(S.score/S.deck.length*100);return `${header()}<section class="panel result"><em>Session complete</em><h1>${S.score}/${S.deck.length}</h1><p>正答率 ${pct}%</p><div class="score"><span style="width:${pct}%"></span></div><div class="miss"><h2>間違えた問題 <b>${S.miss.length}</b></h2>${S.miss.length?S.miss.map((m,i)=>`<div><span>#${i+1}</span><strong>${S.mode}</strong><i>${m}</i></div>`).join(""):'<p class="perfect">All clear. 完璧です。</p>'}</div><button class="secondary" id="again">同じ設定でもう一度</button><button class="text" id="settings">設定を変更</button><button class="text" id="home">モード選択へ</button></section>`}
function render(){app.innerHTML=S.page==="home"?home():S.page==="settings"?settings():S.page==="play"?play():result();bind()}
function pool(k,v){let a=S[k];if(a.includes(v)){if(a.length>1)S[k]=a.filter(x=>x!==v)}else S[k]=[...a,v].sort((a,b)=>a-b);render()}
function bind(){document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;S.page="settings";render()});document.querySelectorAll("[data-string]").forEach(b=>b.onclick=()=>pool("strings",+b.dataset.string));document.querySelectorAll("[data-count]").forEach(b=>b.onclick=()=>{S.count=+b.dataset.count;render()});document.querySelectorAll("[data-note-pool]").forEach(b=>b.onclick=()=>pool("notePool",+b.dataset.notePool));document.querySelectorAll("[data-int-pool]").forEach(b=>b.onclick=()=>pool("intPool",+b.dataset.intPool));document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>{S.intPool={easy:[3,4,7,10],basic:[2,3,4,5,7,9,10],all:[0,1,2,3,4,5,6,7,8,9,10,11]}[b.dataset.preset];render()});document.querySelectorAll("[data-pos]").forEach(b=>b.onclick=()=>{if(S.locked)return;let [s,f]=b.dataset.pos.split(",").map(Number),x=S.picked.find(p=>p.string===s&&p.fret===f);S.picked=x?S.picked.filter(p=>p!==x):[...S.picked,{string:s,fret:f}];render()});document.querySelectorAll("[data-note-answer]").forEach(b=>b.onclick=()=>{let q=S.deck[S.i],v=+b.dataset.noteAnswer;done(v===q.note,NOTES[q.note],`${q.string}弦 ${q.fret}F → ${NOTES[q.note]}`)});document.querySelectorAll("[data-int-answer]").forEach(b=>b.onclick=()=>{let q=S.deck[S.i],v=+b.dataset.intAnswer;done(v===q.semi,INTS[q.semi],INTS[q.semi])});let e=document.querySelector("#from");if(e)e.onchange=()=>{S.from=+e.value;if(S.from>S.to)S.to=S.from;render()};e=document.querySelector("#to");if(e)e.onchange=()=>{S.to=+e.value;if(S.to<S.from)S.from=S.to;render()};e=document.querySelector("#start");if(e)e.onclick=start;e=document.querySelector("#submit");if(e)e.onclick=submitFind;e=document.querySelector("#exit");if(e)e.onclick=()=>{S.page="settings";render()};e=document.querySelector("#again");if(e)e.onclick=start;e=document.querySelector("#settings");if(e)e.onclick=()=>{S.page="settings";render()};document.querySelectorAll("#home").forEach(e=>e.onclick=()=>{S.page="home";render()})}render();
