const NOTES=["C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B"],OPEN=[4,11,7,2,9,4];
let state={screen:"setup",strings:[1,2,3,4,5,6],from:1,to:12,count:20,deck:[],index:0,correct:0,misses:[],locked:false};
const noteAt=(s,f)=>NOTES[(OPEN[s-1]+f)%12];
function deck(){const p=[];state.strings.forEach(s=>{for(let f=state.from;f<=state.to;f++)p.push({string:s,fret:f,note:noteAt(s,f)})});p.sort(()=>Math.random()-.5);return Array.from({length:state.count},(_,i)=>p[i%p.length])}
function start(custom){Object.assign(state,{screen:"practice",deck:custom||deck(),index:0,correct:0,misses:[],locked:false});render()}
function header(){return '<header class="brand"><span>12</span><div><strong>Fretboard</strong><small>Note trainer</small></div></header>'}
function setup(){return `${header()}<section class="panel"><div class="intro"><em>Standard tuning</em><h1>Know every note.<br>Without the guitar.</h1><p>出題範囲を選び、指板上の位置から音名を答えます。</p></div>
<fieldset><legend>Strings <small>出題する弦</small></legend><div class="string-grid">${[1,2,3,4,5,6].map(s=>`<button data-string="${s}" class="${state.strings.includes(s)?"selected":""}"><b>${s}</b><i>${["E","B","G","D","A","E"][s-1]}</i></button>`).join("")}</div></fieldset>
<fieldset><legend>Fret range <small>${state.from}–${state.to} fret</small></legend><div class="range"><label>From<select id="from">${options(state.from)}</select></label><span>—</span><label>To<select id="to">${options(state.to)}</select></label></div></fieldset>
<fieldset><legend>Questions</legend><div class="segments">${[10,20,50].map(n=>`<button data-count="${n}" class="${state.count===n?"selected":""}">${n}</button>`).join("")}</div></fieldset><button class="primary" id="start">Start session <span>→</span></button></section>`}
function options(selected){return Array.from({length:12},(_,i)=>i+1).map(n=>`<option ${n===selected?"selected":""}>${n}</option>`).join("")}
function practice(){const q=state.deck[state.index],frets=Array.from({length:state.to-state.from+1},(_,i)=>state.from+i);return `${header()}<section><div class="progress"><button id="close">×</button><div><span style="width:${(state.index+1)/state.deck.length*100}%"></span></div><b>${state.index+1}<small> / ${state.deck.length}</small></b></div><div class="prompt"><em>Name this note</em><h1>${q.string}弦・${q.fret}フレット</h1></div>
<div class="board-wrap"><div class="numbers">${frets.map(f=>`<span>${f}</span>`).join("")}</div><div class="board">${[1,2,3,4,5,6].map(s=>`<div class="string">${frets.map(f=>`<div class="fret">${s===q.string&&f===q.fret?"<i>?</i>":""}</div>`).join("")}</div>`).join("")}</div></div>
<div class="answers">${NOTES.map(n=>`<button data-note="${n}">${n}</button>`).join("")}</div><div class="feedback">音名を選んでください</div></section>`}
function result(){const pct=Math.round(state.correct/state.deck.length*100);return `${header()}<section class="panel result"><em>Session complete</em><h1>${state.correct}/${state.deck.length}</h1><p>正答率 ${pct}%</p><div class="score"><span style="width:${pct}%"></span></div><div class="miss"><h2>間違えた位置 <b>${state.misses.length}</b></h2>${state.misses.length?state.misses.map(m=>`<div><span>${m.string}弦</span><strong>${m.fret} fret</strong><i>${m.answers.join(", ")} → <b>${m.note}</b></i></div>`).join(""):'<p class="perfect">All clear. 完璧です。</p>'}</div>${state.misses.length?'<button class="primary" id="review">間違えた問題を復習 <span>↻</span></button>':""}<button class="secondary" id="again">同じ範囲でもう一度</button><button class="text" id="settings">設定を変更</button></section>`}
function render(){app.innerHTML=state.screen==="setup"?setup():state.screen==="practice"?practice():result();bind()}
function bind(){document.querySelectorAll("[data-string]").forEach(b=>b.onclick=()=>{let s=+b.dataset.string;if(state.strings.includes(s)){if(state.strings.length>1)state.strings=state.strings.filter(x=>x!==s)}else state.strings.push(s);render()});document.querySelectorAll("[data-count]").forEach(b=>b.onclick=()=>{state.count=+b.dataset.count;render()});let f=document.querySelector("#from"),t=document.querySelector("#to");if(f)f.onchange=()=>{state.from=+f.value;if(state.from>state.to)state.to=state.from;render()};if(t)t.onchange=()=>{state.to=+t.value;if(state.to<state.from)state.from=state.to;render()};let el=document.querySelector("#start");if(el)el.onclick=()=>start();el=document.querySelector("#close");if(el)el.onclick=()=>{state.screen="setup";render()};document.querySelectorAll("[data-note]").forEach(b=>b.onclick=()=>answer(b));el=document.querySelector("#review");if(el)el.onclick=()=>start(state.misses.map(({string,fret,note})=>({string,fret,note})).sort(()=>Math.random()-.5));el=document.querySelector("#again");if(el)el.onclick=()=>start();el=document.querySelector("#settings");if(el)el.onclick=()=>{state.screen="setup";render()}}
function answer(button){if(state.locked)return;state.locked=true;const q=state.deck[state.index],value=button.dataset.note,ok=value===q.note;if(ok)state.correct++;else{let m=state.misses.find(x=>x.string===q.string&&x.fret===q.fret);m?m.answers.push(value):state.misses.push({...q,answers:[value]})}button.classList.add(ok?"right":"wrong");document.querySelector(".fret i").textContent=q.note;document.querySelector(".fret i").classList.add(ok?"right":"wrong");document.querySelector(".feedback").textContent=ok?"Correct":`${value} ではなく ${q.note}`;setTimeout(()=>{state.locked=false;if(++state.index>=state.deck.length)state.screen="result";render()},ok?550:1050)}
render();
